"""
Services Microservice URLs
URL patterns for all services-related endpoints
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ServiceCategoryViewSet, ServiceProviderViewSet, ServiceViewSet,
    ServiceBookingViewSet, ServiceReviewViewSet, ServiceAvailabilityViewSet,
    ServiceCertificationViewSet
)

# Create router and register viewsets
router = DefaultRouter()
router.register(r'categories', ServiceCategoryViewSet, basename='servicecategory')
router.register(r'providers', ServiceProviderViewSet, basename='serviceprovider')
router.register(r'services', ServiceViewSet, basename='service')
router.register(r'bookings', ServiceBookingViewSet, basename='servicebooking')
router.register(r'reviews', ServiceReviewViewSet, basename='servicereview')
router.register(r'availability', ServiceAvailabilityViewSet, basename='serviceavailability')
router.register(r'certifications', ServiceCertificationViewSet, basename='servicecertification')

app_name = 'services'

urlpatterns = [
    path('api/v1/services/', include(router.urls)),
    
    # Additional custom endpoints can be added here
    # path('api/v1/services/search/', views.ServiceSearchView.as_view(), name='service-search'),
    # path('api/v1/services/recommendations/', views.ServiceRecommendationView.as_view(), name='service-recommendations'),
]

# URL patterns generated by the router:
"""
Services Categories:
- GET /api/v1/services/categories/ - List all categories
- GET /api/v1/services/categories/{slug}/ - Get category details
- GET /api/v1/services/categories/{slug}/services/ - Get services in category
- GET /api/v1/services/categories/{slug}/providers/ - Get providers in category

Service Providers:
- GET /api/v1/services/providers/ - List all providers
- POST /api/v1/services/providers/ - Create new provider
- GET /api/v1/services/providers/{slug}/ - Get provider details
- PUT /api/v1/services/providers/{slug}/ - Update provider
- PATCH /api/v1/services/providers/{slug}/ - Partial update provider
- DELETE /api/v1/services/providers/{slug}/ - Delete provider
- GET /api/v1/services/providers/{slug}/services/ - Get provider's services
- GET /api/v1/services/providers/{slug}/availability/ - Get provider availability
- GET /api/v1/services/providers/{slug}/reviews/ - Get provider reviews
- GET /api/v1/services/providers/{slug}/stats/ - Get provider statistics
- GET /api/v1/services/providers/featured/ - Get featured providers
- GET /api/v1/services/providers/top-rated/ - Get top-rated providers

Services:
- GET /api/v1/services/services/ - List all services
- POST /api/v1/services/services/ - Create new service
- GET /api/v1/services/services/{slug}/ - Get service details
- PUT /api/v1/services/services/{slug}/ - Update service
- PATCH /api/v1/services/services/{slug}/ - Partial update service
- DELETE /api/v1/services/services/{slug}/ - Delete service
- GET /api/v1/services/services/{slug}/availability/ - Get service availability
- GET /api/v1/services/services/{slug}/reviews/ - Get service reviews
- GET /api/v1/services/services/{slug}/similar/ - Get similar services
- POST /api/v1/services/services/{slug}/book/ - Book this service
- GET /api/v1/services/services/featured/ - Get featured services
- GET /api/v1/services/services/popular/ - Get popular services
- GET /api/v1/services/services/categories-summary/ - Get services by categories

Service Bookings:
- GET /api/v1/services/bookings/ - List all bookings
- POST /api/v1/services/bookings/ - Create new booking
- GET /api/v1/services/bookings/{id}/ - Get booking details
- PUT /api/v1/services/bookings/{id}/ - Update booking
- PATCH /api/v1/services/bookings/{id}/ - Partial update booking
- DELETE /api/v1/services/bookings/{id}/ - Delete booking
- POST /api/v1/services/bookings/{id}/confirm/ - Confirm booking
- POST /api/v1/services/bookings/{id}/cancel/ - Cancel booking
- POST /api/v1/services/bookings/{id}/start-service/ - Start service
- POST /api/v1/services/bookings/{id}/complete-service/ - Complete service
- GET /api/v1/services/bookings/my-bookings/ - Get user's bookings
- GET /api/v1/services/bookings/provider-bookings/ - Get provider's bookings

Service Reviews:
- GET /api/v1/services/reviews/ - List all reviews
- POST /api/v1/services/reviews/ - Create new review
- GET /api/v1/services/reviews/{id}/ - Get review details
- PUT /api/v1/services/reviews/{id}/ - Update review
- PATCH /api/v1/services/reviews/{id}/ - Partial update review
- DELETE /api/v1/services/reviews/{id}/ - Delete review
- POST /api/v1/services/reviews/{id}/respond/ - Provider response to review
- GET /api/v1/services/reviews/my-reviews/ - Get user's reviews

Service Availability:
- GET /api/v1/services/availability/ - List availability slots
- POST /api/v1/services/availability/ - Create availability slot
- GET /api/v1/services/availability/{id}/ - Get availability details
- PUT /api/v1/services/availability/{id}/ - Update availability
- PATCH /api/v1/services/availability/{id}/ - Partial update availability
- DELETE /api/v1/services/availability/{id}/ - Delete availability
- POST /api/v1/services/availability/bulk-create/ - Create multiple slots
- POST /api/v1/services/availability/bulk-update/ - Update multiple slots

Service Certifications:
- GET /api/v1/services/certifications/ - List certifications
- POST /api/v1/services/certifications/ - Create certification
- GET /api/v1/services/certifications/{id}/ - Get certification details
- PUT /api/v1/services/certifications/{id}/ - Update certification
- PATCH /api/v1/services/certifications/{id}/ - Partial update certification
- DELETE /api/v1/services/certifications/{id}/ - Delete certification
- POST /api/v1/services/certifications/{id}/verify/ - Verify certification
- GET /api/v1/services/certifications/expiring-soon/ - Get expiring certifications
"""
